// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: data.proto

#include "data.pb.h"
#include "data.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Myservice_method_names[] = {
  "/Myservice/MyMethod",
};

std::unique_ptr< Myservice::Stub> Myservice::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Myservice::Stub> stub(new Myservice::Stub(channel, options));
  return stub;
}

Myservice::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_MyMethod_(Myservice_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Myservice::Stub::MyMethod(::grpc::ClientContext* context, const ::MyRequest& request, ::MyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MyRequest, ::MyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MyMethod_, context, request, response);
}

void Myservice::Stub::async::MyMethod(::grpc::ClientContext* context, const ::MyRequest* request, ::MyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MyRequest, ::MyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyMethod_, context, request, response, std::move(f));
}

void Myservice::Stub::async::MyMethod(::grpc::ClientContext* context, const ::MyRequest* request, ::MyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MyResponse>* Myservice::Stub::PrepareAsyncMyMethodRaw(::grpc::ClientContext* context, const ::MyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::MyResponse, ::MyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MyMethod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::MyResponse>* Myservice::Stub::AsyncMyMethodRaw(::grpc::ClientContext* context, const ::MyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMyMethodRaw(context, request, cq);
  result->StartCall();
  return result;
}

Myservice::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Myservice_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Myservice::Service, ::MyRequest, ::MyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Myservice::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MyRequest* req,
             ::MyResponse* resp) {
               return service->MyMethod(ctx, req, resp);
             }, this)));
}

Myservice::Service::~Service() {
}

::grpc::Status Myservice::Service::MyMethod(::grpc::ServerContext* context, const ::MyRequest* request, ::MyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


